// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Un agente de IA de chatbot de asistencia para estudiantes.
 *
 * - studentChatbotAssistance - Una función que maneja el proceso de asistencia del chatbot para estudiantes.
 * - StudentChatbotAssistanceInput - El tipo de entrada para la función studentChatbotAssistance.
 * - StudentChatbotAssistanceOutput - El tipo de retorno para la función studentChatbotAssistance.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const StudentChatbotAssistanceInputSchema = z.object({
  question: z.string().describe('La pregunta que el estudiante está haciendo sobre el material del curso.'),
  courseMaterial: z.string().describe('El material del curso relevante para la pregunta del estudiante.'),
});
export type StudentChatbotAssistanceInput = z.infer<typeof StudentChatbotAssistanceInputSchema>;

const StudentChatbotAssistanceOutputSchema = z.object({
  answer: z.string().describe('La respuesta del chatbot que proporciona orientación y pistas al estudiante.'),
});
export type StudentChatbotAssistanceOutput = z.infer<typeof StudentChatbotAssistanceOutputSchema>;

export async function studentChatbotAssistance(input: StudentChatbotAssistanceInput): Promise<StudentChatbotAssistanceOutput> {
  return studentChatbotAssistanceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'studentChatbotAssistancePrompt',
  input: {schema: StudentChatbotAssistanceInputSchema},
  output: {schema: StudentChatbotAssistanceOutputSchema},
  prompt: `Eres StudiaChat, un útil chatbot asistente para estudiantes en Bolivia.

Tu objetivo es guiar al estudiante para que descubra la solución por sí mismo. Responde siempre en español.

Material del Curso: {{{courseMaterial}}}

Pregunta: {{{question}}}

Respuesta:`,
});

const studentChatbotAssistanceFlow = ai.defineFlow(
  {
    name: 'studentChatbotAssistanceFlow',
    inputSchema: StudentChatbotAssistanceInputSchema,
    outputSchema: StudentChatbotAssistanceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
